import Head from "next/head";
import { Layout } from "../components/layout";
import { Header } from "../components/header";
export default function Home() {
  return (
    <>
      <Head>
        <title>Favorite Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header />
        <input
          type="text"
          placeholder="What's Your Favorite Pokemon?"
          className="w-1/2 text-center mt-12 border-2 border-black rounded-lg"
        />
      </Layout>
    </>
  );
}
